install: gradle wrapper --gradle-version 5.4.1
language: android
android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.1.0

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

before_script:
  - chmod a+x gradlew
  - chmod a+x gradle/wrapper/gradle-wrapper.jar

script: gradlew build